# Generated by Django 5.2.12 on 2026-04-01 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_stock", models.IntegerField(default=0)),
                ("fba_stock", models.IntegerField(default=0)),
                ("sixty_day_sales", models.IntegerField(default=0)),
                ("thirty_day_sales", models.IntegerField(default=0)),
                ("optimal_stock_30d", models.IntegerField(default=0)),
                ("stock_deficit", models.IntegerField(default=0)),
                ("last_count_date", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product__m_number"],
            },
        ),
    ]
