# Generated by Django 5.2.13 on 2026-04-09 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0006_alter_product_blank_family_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FNSKUSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marketplace", models.CharField(max_length=10)),
                ("ran_at", models.DateTimeField()),
                ("created", models.IntegerField(default=0)),
                ("updated", models.IntegerField(default=0)),
                ("unmatched_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-ran_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marketplace",
                    models.CharField(
                        choices=[
                            ("UK", "Amazon UK"),
                            ("US", "Amazon US"),
                            ("CA", "Amazon CA"),
                            ("AU", "Amazon AU"),
                            ("DE", "Amazon DE"),
                            ("ALL", "All marketplaces"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[
                            ("FNSKU", "Amazon FNSKU"),
                            ("UPC", "Manufacturer UPC"),
                            ("EAN", "Manufacturer EAN"),
                        ],
                        max_length=10,
                    ),
                ),
                ("barcode_value", models.CharField(db_index=True, max_length=32)),
                (
                    "label_title",
                    models.CharField(
                        help_text="Text printed on the label (product title, max 80 chars)",
                        max_length=80,
                    ),
                ),
                ("condition", models.CharField(default="New", max_length=20)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("sp_api", "SP-API sync"),
                            ("manual", "Manual entry"),
                            ("csv_import", "CSV import"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "command_payload",
                    models.TextField(
                        help_text="Rendered printer command string (ZPL by default) including quantity directive"
                    ),
                ),
                (
                    "command_language",
                    models.CharField(
                        default="zpl",
                        help_text="Command language of the payload (for debugging/logging)",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed by agent"),
                            ("printing", "Printing"),
                            ("done", "Done"),
                            ("error", "Error"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(
                        blank=True,
                        help_text="Hostname of the agent that claimed this job",
                        max_length=64,
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "barcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_jobs",
                        to="barcodes.productbarcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="productbarcode",
            index=models.Index(
                fields=["product", "marketplace"], name="barcodes_pr_product_b85d11_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productbarcode",
            unique_together={("product", "marketplace", "barcode_type")},
        ),
        migrations.AddIndex(
            model_name="printjob",
            index=models.Index(
                fields=["status", "created_at"], name="barcodes_pr_status_ca0a93_idx"
            ),
        ),
    ]
