# Generated by Django 5.2.13 on 2026-04-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barcodes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Display name, e.g. "Ben & Ivan PM-2411-BT"',
                        max_length=80,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='Stable id agents use to identify themselves, e.g. "pm-2411-bt-fac1"',
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("tcp", "TCP socket"),
                            ("serial", "Serial / Bluetooth tty"),
                            ("cups", "CUPS queue"),
                        ],
                        default="tcp",
                        max_length=10,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="host:port (tcp), /dev/rfcomm0 (serial), or queue-name (cups)",
                        max_length=200,
                    ),
                ),
                (
                    "command_language",
                    models.CharField(
                        choices=[
                            ("zpl", "ZPL (Zebra)"),
                            ("tspl", "TSPL (TSC / Postek)"),
                            ("escpos", "ESC/POS"),
                        ],
                        default="zpl",
                        max_length=10,
                    ),
                ),
                ("label_width_mm", models.PositiveIntegerField(default=50)),
                ("label_height_mm", models.PositiveIntegerField(default=25)),
                ("label_dpi", models.PositiveIntegerField(default=203)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="printjob",
            name="printer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="barcodes.printer",
            ),
        ),
    ]
