# Generated by Django 5.2.12 on 2026-04-01 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "m_number",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("description", models.CharField(max_length=500)),
                ("blank", models.CharField(db_index=True, max_length=50)),
                ("material", models.CharField(blank=True, max_length=100)),
                ("is_personalised", models.BooleanField(default=False)),
                ("do_not_restock", models.BooleanField(default=False)),
                ("do_not_restock_reason", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("in_progress", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["m_number"],
            },
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(db_index=True, max_length=100)),
                ("new_sku", models.CharField(blank=True, max_length=100)),
                ("asin", models.CharField(blank=True, db_index=True, max_length=20)),
                ("fnsku", models.CharField(blank=True, max_length=20)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("UK", "UK"),
                            ("US", "USA"),
                            ("CA", "Canada"),
                            ("AU", "Australia"),
                            ("FR", "France"),
                            ("DE", "Germany"),
                            ("EBAY", "eBay"),
                            ("ETSY", "Etsy"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product__m_number", "channel"],
                "unique_together": {("sku", "channel")},
            },
        ),
    ]
