# Generated by Django 5.2.12 on 2026-04-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sku",
            name="channel",
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
