# Generated by Django 5.2.12 on 2026-04-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_blank_family_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shipping_height_cm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_length_cm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_weight_g",
            field=models.PositiveIntegerField(
                blank=True, help_text="Packed weight in grams", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_width_cm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
    ]
