# Generated by Django 5.2.12 on 2026-04-11 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0009_blanktype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("ebay", "eBay")], max_length=20, unique=True
                    ),
                ),
                ("refresh_token", models.TextField()),
                ("access_token", models.TextField(blank=True)),
                (
                    "access_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scope",
                    models.TextField(
                        blank=True,
                        help_text="Space-separated OAuth scopes granted by the user consent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManualSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("sale_date", models.DateField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("amazon_uk", "Amazon UK"),
                            ("amazon_us", "Amazon US"),
                            ("amazon_ca", "Amazon CA"),
                            ("amazon_au", "Amazon AU"),
                            ("amazon_de", "Amazon DE"),
                            ("amazon_fr", "Amazon FR"),
                            ("amazon_es", "Amazon ES"),
                            ("amazon_nl", "Amazon NL"),
                            ("amazon_it", "Amazon IT"),
                            ("etsy", "Etsy"),
                            ("ebay", "eBay"),
                            ("footfall", "Footfall"),
                            ("shop", "Shop (stub)"),
                        ],
                        default="footfall",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalesVelocityAPICall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("amazon_uk", "Amazon UK"),
                            ("amazon_us", "Amazon US"),
                            ("amazon_ca", "Amazon CA"),
                            ("amazon_au", "Amazon AU"),
                            ("amazon_de", "Amazon DE"),
                            ("amazon_fr", "Amazon FR"),
                            ("amazon_es", "Amazon ES"),
                            ("amazon_nl", "Amazon NL"),
                            ("amazon_it", "Amazon IT"),
                            ("etsy", "Etsy"),
                            ("ebay", "eBay"),
                            ("footfall", "Footfall"),
                            ("shop", "Shop (stub)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("endpoint", models.CharField(max_length=120)),
                ("request_params", models.JSONField(blank=True, null=True)),
                ("response_status", models.IntegerField(null=True)),
                (
                    "response_body",
                    models.JSONField(
                        blank=True,
                        help_text="PII-stripped. Adapters must whitelist keys to persist.",
                        null=True,
                    ),
                ),
                ("duration_ms", models.IntegerField(null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "-created_at"],
                        name="sales_veloc_channel_8c790e_idx",
                    ),
                    models.Index(
                        fields=["response_status"],
                        name="sales_veloc_respons_0de96d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DriftAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detected_at", models.DateTimeField()),
                ("current_velocity", models.PositiveIntegerField()),
                ("rolling_avg_velocity", models.PositiveIntegerField()),
                ("variance_pct", models.DecimalField(decimal_places=2, max_digits=6)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_drift_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["acknowledged", "-detected_at"],
                        name="sales_veloc_acknowl_17c009_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesVelocityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("amazon_uk", "Amazon UK"),
                            ("amazon_us", "Amazon US"),
                            ("amazon_ca", "Amazon CA"),
                            ("amazon_au", "Amazon AU"),
                            ("amazon_de", "Amazon DE"),
                            ("amazon_fr", "Amazon FR"),
                            ("amazon_es", "Amazon ES"),
                            ("amazon_nl", "Amazon NL"),
                            ("amazon_it", "Amazon IT"),
                            ("etsy", "Etsy"),
                            ("ebay", "eBay"),
                            ("footfall", "Footfall"),
                            ("shop", "Shop (stub)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                ("units_sold_30d", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="velocity_snapshots",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sales velocity history",
                "indexes": [
                    models.Index(
                        fields=["product", "snapshot_date"],
                        name="sales_veloc_product_313df6_idx",
                    )
                ],
                "unique_together": {("product", "channel", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="UnmatchedSKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("amazon_uk", "Amazon UK"),
                            ("amazon_us", "Amazon US"),
                            ("amazon_ca", "Amazon CA"),
                            ("amazon_au", "Amazon AU"),
                            ("amazon_de", "Amazon DE"),
                            ("amazon_fr", "Amazon FR"),
                            ("amazon_es", "Amazon ES"),
                            ("amazon_nl", "Amazon NL"),
                            ("amazon_it", "Amazon IT"),
                            ("etsy", "Etsy"),
                            ("ebay", "eBay"),
                            ("footfall", "Footfall"),
                            ("shop", "Shop (stub)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_sku", models.CharField(db_index=True, max_length=120)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("units_sold_30d", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateField()),
                ("last_seen", models.DateField()),
                (
                    "ignored",
                    models.BooleanField(
                        default=False,
                        help_text="True if a user explicitly ignored this SKU via the tab UI",
                    ),
                ),
                (
                    "resolved_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Unmatched SKUs",
                "unique_together": {("channel", "external_sku")},
            },
        ),
    ]
