# Generated by Django 5.2.12 on 2026-04-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales_velocity", "0002_register_daily_schedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manualsale",
            options={"ordering": ["-sale_date", "-created_at"]},
        ),
    ]
