# Generated by Django 5.2.12 on 2026-04-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restock', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='restockitem',
            new_name='restock_res_marketp_e42ace_idx',
            old_name='restock_ite_marketp_idx',
        ),
        migrations.RenameIndex(
            model_name='restockitem',
            new_name='restock_res_m_numbe_b7ac90_idx',
            old_name='restock_ite_m_numbe_idx',
        ),
        migrations.RenameIndex(
            model_name='restockitem',
            new_name='restock_res_alert_3ca658_idx',
            old_name='restock_ite_alert_idx',
        ),
        migrations.RenameIndex(
            model_name='restockreport',
            new_name='restock_res_marketp_64a3cd_idx',
            old_name='restock_rep_marketp_idx',
        ),
    ]
