# Generated by Django 5.2.12 on 2026-04-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restock', '0002_add_restock_exclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('m_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('added_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['m_number'],
            },
        ),
    ]
