# Generated by Django 5.2.13 on 2026-04-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restock", "0003_add_restock_exclusion_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="restockitem",
            name="units_reserved",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restockitem",
            name="units_unfulfillable",
            field=models.IntegerField(default=0),
        ),
    ]
