# Generated by Django 5.2.13 on 2026-04-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restock", "0004_add_reserved_unfulfillable_to_restockitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="restockitem",
            name="units_sold_60d",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restockitem",
            name="units_sold_7d",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restockitem",
            name="units_sold_90d",
            field=models.IntegerField(default=0),
        ),
    ]
