# Generated by Django 5.2.12 on 2026-04-02 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_sku_channel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_id", models.CharField(db_index=True, max_length=50)),
                ("channel", models.CharField(blank=True, max_length=100)),
                ("order_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("made", "Made"),
                            ("dispatched", "Dispatched"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("quantity", models.IntegerField(default=1)),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("flags", models.CharField(blank=True, max_length=500)),
                ("line1", models.CharField(blank=True, max_length=500)),
                ("line2", models.CharField(blank=True, max_length=500)),
                ("line3", models.CharField(blank=True, max_length=500)),
                ("line4", models.CharField(blank=True, max_length=500)),
                ("line5", models.CharField(blank=True, max_length=500)),
                ("line6", models.CharField(blank=True, max_length=500)),
                ("line7", models.CharField(blank=True, max_length=500)),
                ("graphic", models.CharField(blank=True, max_length=500)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("stock_updated", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_dispatch_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_dispatch_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_orders",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date", "-created_at"],
            },
        ),
    ]
