# Generated by Django 5.2.13 on 2026-04-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d2c", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalisedSKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(db_index=True, max_length=100, unique=True)),
                ("colour", models.CharField(blank=True, db_index=True, max_length=50)),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Blank shape / family, e.g. "Regular Stake", "Heart Stake", "Large Metal"',
                        max_length=100,
                    ),
                ),
                (
                    "decoration_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Graphic", "Graphic"),
                            ("Photo", "Photo"),
                            ("None", "None"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional theme e.g. Pet, Baby, Islamic",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "ordering": ["product_type", "colour", "sku"],
            },
        ),
    ]
