# Generated by Django 5.2.13 on 2026-04-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d2c", "0002_add_personalised_sku"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTypeBlanks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_type",
                    models.CharField(
                        db_index=True,
                        help_text='Matches PersonalisedSKU.product_type, e.g. "Regular Stake"',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "blank_names",
                    models.CharField(
                        blank=True,
                        help_text='Comma-separated blank names, e.g. "Tom (acrylic), Dick (aluminium)"',
                        max_length=500,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Product type blanks",
                "ordering": ["product_type"],
            },
        ),
    ]
