# Generated by Django 5.2.13 on 2026-04-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d2c", "0003_add_product_type_blanks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColourBlanks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "colour",
                    models.CharField(
                        db_index=True,
                        help_text='Matches PersonalisedSKU.colour, e.g. "Silver"',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "blank_names",
                    models.CharField(
                        blank=True,
                        help_text='Comma-separated blank names, e.g. "Dick (aluminium face, CNC cut)"',
                        max_length=500,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Colour blanks",
                "ordering": ["colour"],
            },
        ),
    ]
