# Generated by Django 5.2.13 on 2026-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d2c", "0004_add_colour_blanks"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchorder",
            name="is_external_shipment",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
