# Generated by Django 5.2.12 on 2026-04-01 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("master_stock", "Master Stock"),
                            ("assembly", "Assembly (SKU Mapping)"),
                            ("sku_assignment", "SKU Assignment"),
                            ("scratchpad", "ScratchPad2 (Optimal Stock)"),
                            ("fba_inventory", "FBA Inventory Report"),
                            ("sales_traffic", "Sales & Traffic Report"),
                            ("restock", "Restock Inventory Report"),
                            ("procurement", "Procurement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                ("rows_processed", models.IntegerField(default=0)),
                ("rows_created", models.IntegerField(default=0)),
                ("rows_updated", models.IntegerField(default=0)),
                ("rows_skipped", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                (
                    "imported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
