# Generated by Django 5.2.12 on 2026-04-10 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0008_shipping_dimensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FBAShipmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name, e.g. 'FBA UK 2026-04-15'",
                        max_length=120,
                    ),
                ),
                (
                    "marketplace",
                    models.CharField(
                        choices=[
                            ("UK", "Amazon UK"),
                            ("US", "Amazon US"),
                            ("CA", "Amazon CA"),
                            ("AU", "Amazon AU"),
                            ("DE", "Amazon DE"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ship_from_address",
                    models.JSONField(
                        help_text="Snapshot of NBNE ship-from address at creation time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("items_added", "Items added"),
                            ("plan_creating", "Creating inbound plan"),
                            ("plan_created", "Inbound plan created"),
                            ("packing_generating", "Generating packing options"),
                            ("packing_options_fetching", "Fetching packing options"),
                            ("packing_options_ready", "Packing options available"),
                            ("packing_info_setting", "Setting packing information"),
                            ("packing_info_set", "Packing information set"),
                            ("packing_confirming", "Confirming packing option"),
                            ("packing_confirmed", "Packing option confirmed"),
                            ("placement_generating", "Generating placement options"),
                            (
                                "placement_options_fetching",
                                "Fetching placement options",
                            ),
                            ("placement_options_ready", "Placement options available"),
                            ("placement_confirming", "Confirming placement option"),
                            ("placement_confirmed", "Placement confirmed"),
                            (
                                "transport_generating",
                                "Generating transportation options",
                            ),
                            (
                                "transport_options_fetching",
                                "Fetching transportation options",
                            ),
                            (
                                "transport_options_ready",
                                "Transportation options available",
                            ),
                            (
                                "delivery_window_generating",
                                "Generating delivery windows",
                            ),
                            ("delivery_window_fetching", "Fetching delivery windows"),
                            ("delivery_window_ready", "Delivery windows available"),
                            ("transport_confirming", "Confirming transportation"),
                            ("transport_confirmed", "Transportation confirmed"),
                            ("labels_fetching", "Fetching labels"),
                            ("ready_to_ship", "Ready to ship (labels available)"),
                            ("dispatched", "Dispatched to Amazon"),
                            ("cancelled", "Cancelled"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=40,
                    ),
                ),
                (
                    "inbound_plan_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "selected_packing_option_id",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "selected_placement_option_id",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "selected_transportation_option_id",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "selected_delivery_window_id",
                    models.CharField(blank=True, max_length=64),
                ),
                ("current_operation_id", models.CharField(blank=True, max_length=64)),
                (
                    "current_operation_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("error_log", models.JSONField(blank=True, default=list)),
                ("packing_options_snapshot", models.JSONField(blank=True, null=True)),
                ("placement_options_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "transportation_options_snapshot",
                    models.JSONField(blank=True, null=True),
                ),
                ("delivery_window_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fba_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FBAShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment_id",
                    models.CharField(
                        help_text="Amazon shipmentId (pre-confirmation)", max_length=64
                    ),
                ),
                (
                    "shipment_confirmation_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Amazon shipmentConfirmationId, e.g. FBA15ABCDEFG (post-confirmation)",
                        max_length=64,
                    ),
                ),
                (
                    "destination_fc",
                    models.CharField(
                        blank=True,
                        help_text="Destination fulfilment centre code, e.g. LTN4, BHX1",
                        max_length=16,
                    ),
                ),
                ("labels_url", models.URLField(blank=True, max_length=1000)),
                ("labels_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("carrier_name", models.CharField(blank=True, max_length=80)),
                ("tracking_number", models.CharField(blank=True, max_length=120)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="fba_shipments.fbashipmentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["shipment_id"],
            },
        ),
        migrations.CreateModel(
            name="FBABox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("box_number", models.PositiveIntegerField()),
                ("length_cm", models.DecimalField(decimal_places=1, max_digits=6)),
                ("width_cm", models.DecimalField(decimal_places=1, max_digits=6)),
                ("height_cm", models.DecimalField(decimal_places=1, max_digits=6)),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "amazon_box_id",
                    models.CharField(
                        blank=True,
                        help_text="Amazon's assigned box identifier, e.g. FBA15ABCDEFG000001",
                        max_length=64,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Populated after placement confirmation assigns boxes to shipments",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="fba_shipments.fbashipment",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Redundant link to allow pre-placement box creation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="fba_shipments.fbashipmentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "box_number"],
            },
        ),
        migrations.CreateModel(
            name="FBAAPICall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation_name", models.CharField(db_index=True, max_length=80)),
                ("request_body", models.JSONField(blank=True, null=True)),
                ("response_status", models.IntegerField(null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                (
                    "operation_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("duration_ms", models.IntegerField(null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_calls",
                        to="fba_shipments.fbashipmentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FBAShipmentPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("fnsku", models.CharField(max_length=32)),
                ("msku", models.CharField(max_length=80)),
                ("label_owner", models.CharField(default="SELLER", max_length=20)),
                ("prep_owner", models.CharField(default="SELLER", max_length=20)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fba_shipments.fbashipmentplan",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="products.sku"
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "msku"],
            },
        ),
        migrations.CreateModel(
            name="FBABoxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="fba_shipments.fbabox",
                    ),
                ),
                (
                    "plan_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_placements",
                        to="fba_shipments.fbashipmentplanitem",
                    ),
                ),
            ],
            options={
                "ordering": ["box", "plan_item"],
            },
        ),
        migrations.AddIndex(
            model_name="fbashipmentplan",
            index=models.Index(
                fields=["status", "-created_at"], name="fba_shipmen_status_b00d15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fbashipmentplan",
            index=models.Index(
                fields=["marketplace", "status"], name="fba_shipmen_marketp_4d7a0b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fbabox",
            unique_together={("plan", "box_number")},
        ),
        migrations.AddIndex(
            model_name="fbaapicall",
            index=models.Index(
                fields=["plan", "-created_at"], name="fba_shipmen_plan_id_a6225b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fbaapicall",
            index=models.Index(
                fields=["operation_name", "-created_at"],
                name="fba_shipmen_operati_13605e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fbashipmentplanitem",
            unique_together={("plan", "sku")},
        ),
        migrations.AlterUniqueTogether(
            name="fbaboxitem",
            unique_together={("box", "plan_item")},
        ),
    ]
