# Generated by Django 5.2.12 on 2026-04-01 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_sku_channel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("UK", "UK"),
                            ("US", "USA"),
                            ("CA", "Canada"),
                            ("AU", "Australia"),
                            ("FR", "France"),
                            ("DE", "Germany"),
                            ("IT", "Italy"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("packing", "Packing"),
                            ("labelled", "Labelled"),
                            ("shipped", "Shipped"),
                        ],
                        db_index=True,
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("shipment_date", models.DateField(blank=True, null=True)),
                ("total_units", models.IntegerField(default=0)),
                ("box_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-shipment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("quantity", models.IntegerField()),
                ("quantity_shipped", models.IntegerField(default=0)),
                ("box_number", models.IntegerField(blank=True, null=True)),
                ("amz_restock_quantity", models.IntegerField(default=0)),
                ("stock_at_ship", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_items",
                        to="products.product",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["shipment", "box_number", "product__m_number"],
            },
        ),
    ]
