# Generated by Django 5.2.13 on 2026-04-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentitem",
            name="machine_assignment",
            field=models.CharField(
                blank=True,
                choices=[("", "—"), ("STOCK", "STOCK"), ("UV", "UV"), ("SUB", "SUB")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="shipmentitem",
            name="stock_taken",
            field=models.IntegerField(default=0),
        ),
    ]
