# Generated by Django 5.2.13 on 2026-04-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_ivan_review_12_machine_and_stock_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentitem",
            name="item_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
