# Generated by Django 5.2.12 on 2026-04-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("material_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("unit_of_measure", models.CharField(blank=True, max_length=50)),
                ("current_stock", models.IntegerField(default=0)),
                ("reorder_point", models.IntegerField(default=0)),
                ("standard_order_quantity", models.IntegerField(default=0)),
                ("preferred_supplier", models.CharField(blank=True, max_length=200)),
                ("product_page_url", models.URLField(blank=True, max_length=500)),
                ("lead_time_days", models.IntegerField(default=0)),
                ("safety_stock", models.IntegerField(default=0)),
                ("in_house_description", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
