# Generated by Django 5.2.13 on 2026-04-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0006_ivan_review_11_multi_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="simple_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("printed", "Printed"),
                    ("heatpressed", "Heatpressed"),
                    ("laminated", "Laminated"),
                    ("on_bench", "On the bench"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
