# Generated by Django 5.2.13 on 2026-04-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0007_ivan_review_13_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="asap",
            field=models.BooleanField(
                default=False, help_text="If True, job is ASAP (no specific date)"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="customer",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
