# Generated by Django 5.2.13 on 2026-04-16 12:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costs", "0002_refix_composite_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="costconfig",
            name="b2b_monthly_revenue_gbp",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Manual monthly B2B/local/footfall revenue estimate in GBP. Used alongside Amazon, Etsy, and eBay revenue for overhead allocation.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="costconfig",
            name="monthly_overhead_gbp",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("24500.00"),
                help_text="Total monthly fixed overhead (rent, utilities, salaries, etc). Used to compute per-channel overhead allocation.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="blankcost",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text='Human-friendly label, e.g. "Dick + Kirsty". Display only.',
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="blankcost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="blankcost",
            name="is_composite",
            field=models.BooleanField(
                default=False,
                help_text='True for multi-blank names (e.g. "DICK, KIRSTY"). Cost lookup returns LOW confidence for composites unless an M-number override is defined.',
            ),
        ),
        migrations.AlterField(
            model_name="blankcost",
            name="labour_minutes",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Blended labour minutes per unit (all stages combined).",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="blankcost",
            name="material_cost_gbp",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.50"),
                help_text="Materials cost per unit, in GBP, ex-VAT. Prepopulated at £2.50.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="blankcost",
            name="normalized_name",
            field=models.CharField(
                db_index=True,
                help_text="Canonical key produced by costs.models.normalise_blank. Look up via normalise_blank(product.blank).",
                max_length=120,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="blankcost",
            name="product_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cached count of active products whose normalised blank matches. Recomputed by the resync action.",
            ),
        ),
        migrations.AlterField(
            model_name="blankcost",
            name="sample_raw_blank",
            field=models.CharField(
                blank=True,
                help_text="One example of the raw Product.blank string that collapses to this row, for editor context.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="costconfig",
            name="default_material_gbp",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.50"),
                help_text="Material cost used when no BlankCost row matches. Low confidence.",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="costconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="costconfig",
            name="labour_rate_gbp_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Blended labour rate, £/hr. Spec value: £15.",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="costconfig",
            name="overhead_per_unit_gbp",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("6.45"),
                help_text="Fixed overhead allocation per unit, £. Spec value: £6.45 (£24,500 monthly overhead ÷ 3,800 units/month).",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="costconfig",
            name="vat_rate_uk",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.200"),
                help_text="UK VAT rate used by Cairn margin engine to reclaim input VAT on materials. EU VAT is deducted at source by Amazon.",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="mnumbercostoverride",
            name="cost_price_gbp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total all-in cost per unit (material + labour + overhead). Null means the row exists as a placeholder flagged for the user to fill in; cost lookup falls through to BlankCost until set.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mnumbercostoverride",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
