# Generated by Django 5.2.13 on 2026-04-16 12:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costs", "0003_b2b_revenue_and_monthly_overhead"),
    ]

    operations = [
        migrations.AddField(
            model_name="costconfig",
            name="ebay_monthly_revenue_gbp",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Manual monthly eBay revenue estimate in GBP. Will be replaced by API-sourced data when eBay pricing is integrated.",
                max_digits=10,
            ),
        ),
    ]
